import type { NextPage } from "next"
import Head from "next/head"
import { useEffect, useRef, useState } from "react"
import { About, Intro, Navbar, Projects, Skills } from "../components"
import { Contact } from "../components/Contact"
import { Cursor } from "../components/Cursor"
import { ModalContextProvider } from "../contexts"
import styles from "../styles/Home.module.scss"

const Home: NextPage = () => {
  return (
    <ModalContextProvider>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <Cursor />
        <Navbar />
        <Intro />
        <About />
        <Projects />
        <Skills />
        <Contact />
      </div>
    </ModalContextProvider>
  )
}

export default Home
